# Ginger Beer {#ginger-beer}

## Batch 1

**Bug**

*Early September 2021*

Started a ginger bug, chlorine evaporated water from starter sourdough jug.  Arbitrary amount of grated ginger in small amount of initial water.  After about a week added more ginger and a bit of sugar. Started shaking it, got bubbly.

**Bulk Ferment**

*September 18 2021*

- Cut up a few chunks of skinned ginger and simmered in 2 qts of tap water for ~15 minutes.

- Strained out ginger solids

- Added 2 cups sugar, stirred too dissolve

- Added 2 qts of tap and let cool

- Added strained ginger bug

- F1 in cloth covered crock

**Second Ferment**

No notes, but it was pretty good.  Definitely different than commercial versions.

## Batch 2

**Bug**

*May 24-ish, 2022*

Started bug with occasional feedings of arbitrary amounts.  Grew vigorous after a few days, but ran out of ginger mid-covid quarantine so had to wait for a grocery pick up and bug grew stagnant.  Revived with a couple (two) feedings, noticed a *few* bubbles on May 31st.  All feedings used de-chlorinated water left out overnight and ginger (skin included) grated on the fine side of a box grater.

**Bulk Ferment**

*May 31, 2022*

Loosely followed [The Art of Fermentation](https://www.wildfermentation.com/the-art-of-fermentation/) method.

- Simmered 2 quarts of water with ~5 in of coursely grated ginger (skin included, not sure if appropriate to have left it on) for about 15 minutes

- Dissolved ~~2 cups~~ 400 g sugar

- Added 2 quarts cool water to dilute, tasted and let cool to room temp for several hours (very warm day)

- Added bug (slightly less than ~2 cups)

- Mixed then strained through fine mesh sieve

**Output**

Split perfectly between a half-gallon mason jar and a 2 liter kliner jar.
